server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/email_verification
    username: root
    password: Aa28121998
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
# Nếu bạn muốn cấu hình gửi email, hãy bỏ chú thích phần dưới đây
# spring:
#   mail:
#     host: localhost
#     port: 1025
#     username: hello
#     password: hello
#     properties:
#       mail:
#         smtp:
#           ssl:
#             trust: "*"
#           auth: true
#           starttls:
#             enable: true
#           connectiontimeout: 5000
#           timeout: 3000
#           writetimeout: 5
